all: part4 part4.lineclear

part4:
	gcc -Wall part4.c -o part4.exe -I..

part4.lineclear:
	gcc -Wall part4.lineclear.c -o part4.lineclear.exe -I..

clean:
	rm -f part4.exe part4.lineclear.exe

.PHONY: part4 part4.lineclear clean